### ISSUE TITLE
vdsm-tool config-lvm-filter be required packackge lvm2

### ISSUE THREAD

**Issue by blame2020** [oVirt/vdsm#227]
vdsm-tool such as "vdsm-tool config-lvm-filter" subcommand calls command in lvm2 package.
Please add  lvm2 as dependencies in rpm spec.

**Comment by nirs** [comment]
The vdsm package requires lvm2. Do you try to install vdsm-python just to run
vdsm-tool config-lvm-filter?

I think most of the dependencies are at the vdsm meta package so we can require
different packages on different architectures (this is why vdsm is not a noarch
package). But since lvm2 requirement is the same, we can move it to vdsm-python
which anyway install all the code using lvm2.

**Comment by blame2020** [comment]
(I am talking by using google translations)

Thank you for quick response.

>The vdsm package requires lvm2. Do you try to install vdsm-python just to run
vdsm-tool config-lvm-filter?
No.  I use vdsm with of oVirt.

> I think most of the dependencies are at the vdsm meta package so we can require
different packages on different architectures (this is why vdsm is not a noarch
package). But since lvm2 requirement is the same, we can move it to vdsm-python
which anyway install all the code using lvm2.

Personally, I don't think it's okay to add it anywhere as long as it's okay to run vdsm.

**Comment by blame2020** [comment]
I'm sorry. I found that already exists lvm2 as dependencies.
```
# rpm -q --requires vdsm 
...
lvm2 >= 8:2.03
...
```
However, it was not installed in my environment (CentOS Stream 8)...

**Comment by blame2020** [comment]
If you're not mistaken, lvm2 wasn't automatically installed as a dependency. I still don't understand why.

I'll check the reproducibility again.

**Comment by blame2020** [comment]
> I'll check the reproducibility again.

It was installed as expected. sorry
